services:
  # api:
  #   container_name: cmed-api
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cmed_db
  #     - SPRING_DATASOURCE_USERNAME=postgres
  #     - SPRING_DATASOURCE_PASSWORD=secret
  #     - SPRING_DEVTOOLS_RESTART_ENABLED=true
  #     - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./app/src:/app/src
  #   command: ["gradle", "bootRun"]
  
  db:
    image: postgres:16.3-alpine
    container_name: cmed-db
    environment:
      - POSTGRES_DB=cmed_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: